include_recipe 'fueled-core::default'
include_recipe 'fueled-zsh::default'
include_recipe 'fueled-chruby::default'
include_recipe 'fueled-sublime::default'
include_recipe 'fueled-osx-applications::default'
