include_recipe 'fueled-station::oh-my-zsh'
include_recipe 'fueled-station::applications'
include_recipe 'fueled-station::sublime'
include_recipe 'fueled-station::chruby'
include_recipe 'fueled-station::node'
