include_recipe 'chocolatey'
include_recipe 'fueled-windows-apps::ruby-installer'
include_recipe 'fueled-windows-apps::chrome'
include_recipe 'fueled-windows-apps::canary'
include_recipe 'fueled-windows-apps::firefox'
include_recipe 'fueled-windows-apps::github'
include_recipe 'fueled-windows-apps::heroku-toolbelt'
